#!/usr/bin/env ruby
require_relative 'lib/parse_arguments'
require_relative 'lib/environment'

command = ARGV[0]
category = ARGV[1]
options = ParseArguments.parse
options[:name] = ARGV[2]

error_messages = ParseArguments.validate(options)
if error_messages.empty?
  require 'sqlite3'

  db = Environment.database_connection(options[:environment])
  totalMovieIDs = db.execute("SELECT COUNT(*) FROM movies")
  movieID = totalMovieIDs[0][0] + 1

  statement = "insert into movies(movieID,title,year,length,budget,aggregateRating,totalReviews,mpaa,genreID) values (#{movieID},'#{options[:name]}',#{options[:year]},#{options[:length]},#{options[:budget]},NULL,NULL,'#{options[:mpaa]}',#{options[:genre]})"
  db.execute(statement)

  puts "A #{category} titled #{options[:name]} with genre #{options[:genre]}, year #{options[:year]}, length #{options[:length]}, budget #{options[:budget]}, and mpaa #{options[:mpaa]} was created."
else
  puts error_messages
end